services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    Zoglo\ContaoUserInterfaceBackport\:
        resource: '../src/'
        exclude: '../src/{DependencyInjection}'
